name: Release project
on:
  push:
    branches:
      - prod

jobs:
  release:

    name: Release
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release
        uses: huggingface/semver-release-action@latest
