name: Deployment on Staging

on:
  pull_request:
    branches: stage
    types: closed

jobs:
  deployment:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - run: |
        echo Deployed on staging server