name: Deployment on Testing

on:
  pull_request:
    branches: dev
    types: closed

jobs:
  deployment:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    environment: development
    steps:
    - run: |
        echo Deployed on dev server